[profile.default]
src = "contracts"

#out = "out"
#libs = ["lib"]

remappings = [
	'@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
	'@ensdomains/ens-contracts/=lib/ens-contracts/',
	'@eth-optimism/=lib/optimism/packages/'
]

#optimizer = true
#optimizer_runs = 1200

#extra_output = ['storageLayout']

